//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElorMAUI.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElorMAUI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir nuevo centro.
        /// </summary>
        public static string AnadirCentroBtn {
            get {
                return ResourceManager.GetString("AnadirCentroBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        public static string AnteriorBtn {
            get {
                return ResourceManager.GetString("AnteriorBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar por nombre, dirección o municipio....
        /// </summary>
        public static string BuscarPlaceholder {
            get {
                return ResourceManager.GetString("BuscarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string CancelarBtn {
            get {
                return ResourceManager.GetString("CancelarBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando....
        /// </summary>
        public static string CargandoLabel {
            get {
                return ResourceManager.GetString("CargandoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centro no encontrado.
        /// </summary>
        public static string CenterNotFound {
            get {
                return ResourceManager.GetString("CenterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Postal.
        /// </summary>
        public static string CodigoPostalLabel {
            get {
                return ResourceManager.GetString("CodigoPostalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordenadas X.
        /// </summary>
        public static string CoordXLabel {
            get {
                return ResourceManager.GetString("CoordXLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordenada Y.
        /// </summary>
        public static string CoordYLabel {
            get {
                return ResourceManager.GetString("CoordYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear centro.
        /// </summary>
        public static string CrearBtn {
            get {
                return ResourceManager.GetString("CrearBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de.
        /// </summary>
        public static string DeLabel {
            get {
                return ResourceManager.GetString("DeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dependencia.
        /// </summary>
        public static string DependenciaLabel {
            get {
                return ResourceManager.GetString("DependenciaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string DireccionLabel {
            get {
                return ResourceManager.GetString("DireccionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string EditarBtn {
            get {
                return ResourceManager.GetString("EditarBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string EliminarBtn {
            get {
                return ResourceManager.GetString("EliminarBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fax.
        /// </summary>
        public static string FaxLabel {
            get {
                return ResourceManager.GetString("FaxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar centro.
        /// </summary>
        public static string FormTitleEdit {
            get {
                return ResourceManager.GetString("FormTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo centro.
        /// </summary>
        public static string FormTitleNew {
            get {
                return ResourceManager.GetString("FormTitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Género (castellano).
        /// </summary>
        public static string GeneroCastLabel {
            get {
                return ResourceManager.GetString("GeneroCastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Género (Euskera).
        /// </summary>
        public static string GeneroEuLabel {
            get {
                return ResourceManager.GetString("GeneroEuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Género.
        /// </summary>
        public static string GeneroLabel {
            get {
                return ResourceManager.GetString("GeneroLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string GuardarBtn {
            get {
                return ResourceManager.GetString("GuardarBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Latitud.
        /// </summary>
        public static string LatitudLabel {
            get {
                return ResourceManager.GetString("LatitudLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de Centros.
        /// </summary>
        public static string ListaCentrosTitle {
            get {
                return ResourceManager.GetString("ListaCentrosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string LoginContraseña {
            get {
                return ResourceManager.GetString("LoginContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string LoginCorreo {
            get {
                return ResourceManager.GetString("LoginCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud.
        /// </summary>
        public static string LongitudLabel {
            get {
                return ResourceManager.GetString("LongitudLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrando {0} centros.
        /// </summary>
        public static string MostrandoCentros {
            get {
                return ResourceManager.GetString("MostrandoCentros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio (euskera).
        /// </summary>
        public static string MunicipioEuLabel {
            get {
                return ResourceManager.GetString("MunicipioEuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio.
        /// </summary>
        public static string MunicipioLabel {
            get {
                return ResourceManager.GetString("MunicipioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre (Euskera).
        /// </summary>
        public static string NombreEuLabel {
            get {
                return ResourceManager.GetString("NombreEuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string NombreLabel {
            get {
                return ResourceManager.GetString("NombreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página.
        /// </summary>
        public static string PaginaLabel {
            get {
                return ResourceManager.GetString("PaginaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página web.
        /// </summary>
        public static string PaginaWebLabel {
            get {
                return ResourceManager.GetString("PaginaWebLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previsión de los días.
        /// </summary>
        public static string PrevisionDiasLabel {
            get {
                return ResourceManager.GetString("PrevisionDiasLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primero.
        /// </summary>
        public static string PrimeroBtn {
            get {
                return ResourceManager.GetString("PrimeroBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sigueinte.
        /// </summary>
        public static string SiguienteBtn {
            get {
                return ResourceManager.GetString("SiguienteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string TelefonoLabel {
            get {
                return ResourceManager.GetString("TelefonoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temperatura actual.
        /// </summary>
        public static string TemperaturaActualLabel {
            get {
                return ResourceManager.GetString("TemperaturaActualLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Territori (Euskera).
        /// </summary>
        public static string TerritorioEuLabel {
            get {
                return ResourceManager.GetString("TerritorioEuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Territorio.
        /// </summary>
        public static string TerritorioLabel {
            get {
                return ResourceManager.GetString("TerritorioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de centro (Euskera).
        /// </summary>
        public static string TipoCentroEuLabel {
            get {
                return ResourceManager.GetString("TipoCentroEuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de centro.
        /// </summary>
        public static string TipoCentroLabel {
            get {
                return ResourceManager.GetString("TipoCentroLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos.
        /// </summary>
        public static string TodosLabel {
            get {
                return ResourceManager.GetString("TodosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Último.
        /// </summary>
        public static string UltimoBtn {
            get {
                return ResourceManager.GetString("UltimoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver detalles.
        /// </summary>
        public static string VerDetallesBtn {
            get {
                return ResourceManager.GetString("VerDetallesBtn", resourceCulture);
            }
        }
    }
}
